
package com.demo.service.localwsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-27T23:07:27.605+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class IHelloWorld_IHelloWorldPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.demo.com/", "IHelloWorldService");

    private IHelloWorld_IHelloWorldPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
    	/*        URL wsdlURL = IHelloWorldService.WSDL_LOCATION;
        IHelloWorldService ss = new IHelloWorldService(wsdlURL, SERVICE_NAME);
        IHelloWorld port = ss.getIHelloWorldPort();  
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_name = "dd";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_name);
        System.out.println("sayHello.result=" + _sayHello__return);*/
    	
    	/* Set NEW Endpoint Location */  //JAX-WS的写法
    	IHelloWorldService service = new IHelloWorldService();
    	IHelloWorld port = service.getIHelloWorldPort();
    	String endpointURL = "http://localhost:8080/webservice-demo/helloWorld";
    	BindingProvider bp = (BindingProvider)port;
    	bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, endpointURL);
    	java.lang.String _sayHello_name = "xx";
    	System.out.println( port.sayHello(_sayHello_name));
    }

}
