package com.demo.service.localwsdl;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-27T23:07:27.667+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "IHelloWorldService", 
                  wsdlLocation = "classpath:wsdl/helloWorld.wsdl",
                  targetNamespace = "http://service.demo.com/") 
public class IHelloWorldService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.demo.com/", "IHelloWorldService");
    public final static QName IHelloWorldPort = new QName("http://service.demo.com/", "IHelloWorldPort");
    static {
    	 URL url = null;
         url = IHelloWorldService.class.getClassLoader().getResource("wsdl/helloWorld.wsdl");
         WSDL_LOCATION = url;
    }

    public IHelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IHelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloWorldService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IHelloWorld
     */
    @WebEndpoint(name = "IHelloWorldPort")
    public IHelloWorld getIHelloWorldPort() {
        return super.getPort(IHelloWorldPort, IHelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloWorld
     */
    @WebEndpoint(name = "IHelloWorldPort")
    public IHelloWorld getIHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(IHelloWorldPort, IHelloWorld.class, features);
    }

}
