package com.demo.service.localwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-27T23:07:27.667+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.demo.com/", name = "IHelloWorld")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IHelloWorld {

    @WebResult(name = "return", targetNamespace = "http://service.demo.com/", partName = "return")
    @WebMethod
    public java.lang.String sayHello(
        @WebParam(partName = "name", name = "name")
        java.lang.String name
    );
}
